Update ruby.yml

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -13,7 +13,7 @@ jobs:
     strategy:
       matrix:
         ruby-version: ['2.6', '2.7', '3.0']
-        ansible-version: ['2.8', '2.9', '2.10']
+        ansible-version: ['2.8.17', '2.9.17', '2.10.3']
 
     steps:
     - uses: actions/checkout@v2
@@ -33,19 +33,21 @@ jobs:
       run: bundle exec rspec --require spec_helper --format d
     - name: Run rubocop
       run: bundle exec rubocop lib bin spec
-    # - name: Setup ansible
-    #   run: ./test/ansible-setup.sh
+    - name: Setup ansible
+      run: | 
+            pip3 install ansible==${{matrix.ansible-version}}
+            ansible-playbook --version
     - name: integration tests
       run:  |
         echo "${{ matrix.ruby-version }} ${{matrix.ansible-version}}"        
-        # bundle check
-        # bundle exec kitchen test simpleNoChef
-        # bundle exec kitchen test simpleWithChef
-        # bundle exec kitchen test notidempotent | tee /tmp/notidempotent
-        # number_of_servers_in_idempotent="$(bundle exec kitchen list notidempotent | grep Ssh | wc -l |  tr -d '[[:space:]]')"
-        # failed_nonotidempotent=$(cat /tmp/notidempotent | grep "Warning idempotency test \[failed\]" | wc -l |  tr -d '[[:space:]]')
-        # if [ ! "${failed_nonotidempotent}" = "${number_of_servers_in_idempotent}" ] ; then
-        #     echo "Non idempotent tasks '$failed_nonotidempotent' should match '${number_of_servers_in_idempotent}'. :( failed"
-        #     exit 1
-        # fi
+        bundle check
+        bundle exec kitchen test simpleNoChef
+        bundle exec kitchen test simpleWithChef
+        bundle exec kitchen test notidempotent | tee /tmp/notidempotent
+        number_of_servers_in_idempotent="$(bundle exec kitchen list notidempotent | grep Ssh | wc -l |  tr -d '[[:space:]]')"
+        failed_nonotidempotent=$(cat /tmp/notidempotent | grep "Warning idempotency test \[failed\]" | wc -l |  tr -d '[[:space:]]')
+        if [ ! "${failed_nonotidempotent}" = "${number_of_servers_in_idempotent}" ] ; then
+             echo "Non idempotent tasks '$failed_nonotidempotent' should match '${number_of_servers_in_idempotent}'. :( failed"
+             exit 1
+        fi
       
