Update ruby.yml

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -32,4 +32,15 @@ jobs:
       run: bundle exec rspec --require spec_helper --format d
     - name: Run rubocop
       run: bundle exec rubocop lib bin spec
+    - name: integeration tests
+      run:  |
+        bundle exec kitchen test simpleNoChef
+        bundle exec kitchen test simpleWithChef
+        bundle exec kitchen test notidempotent | tee /tmp/notidempotent
+        number_of_servers_in_idempotent="$(bundle exec kitchen list notidempotent | grep Ssh | wc -l |  tr -d '[[:space:]]')"
+        failed_nonotidempotent=$(cat /tmp/notidempotent | grep "Warning idempotency test \[failed\]" | wc -l |  tr -d '[[:space:]]')
+        if [ ! "${failed_nonotidempotent}" = "${number_of_servers_in_idempotent}" ] ; then
+            echo "Non idempotent tasks '$failed_nonotidempotent' should match '${number_of_servers_in_idempotent}'. :( failed"
+            exit 1
+        fi
       
